### PR TITLE
Rule class

### PR DESCRIPTION
**Pull request by MerrowBB**

### CODE REVIEW

**Comment by imitrichev** [comment]
1) destructor should not be pure virtual, but only virtual!
2) AppState() name is not clear. Consider, e.g. "ApplyRule()" instead.
This, now, should not be virtual but should sequentially call two functions: FindNeighbours() and DetermineNewState().
3) We refactor the code with @sGooze and @FanatSors and decided to add two more methods: (pure) virtual FindNeighbours() and virtual DetermineNewState(). Their specific realization would be a task for RuleGameOfLife class programmers, of course.

**Comment by FanatSors** [comment]
Are we english boys and girls now?

**Comment by imitrichev** [comment]
Trying to make ourselfs pro developers. Or is this an overcomplication?

**Comment by imitrichev** [comment]
Trying to make ourselfs pro developers. Or is this an overcomplication?

**Pull request merged**
